package com.waddle2.feishuautopunch;
import android.app.*; import android.content.*; import android.os.*; import android.provider.Settings; import androidx.core.app.NotificationCompat; import java.text.SimpleDateFormat; import java.util.*;
public class AlarmReceiver extends BroadcastReceiver {
 static final String PREF="settings", CHANNEL="feishu_alarm"; static final int BASE=8100;
 static void setEnabled(Context c,boolean v){c.getSharedPreferences(PREF,0).edit().putBoolean("enabled",v).apply();} static boolean isEnabled(Context c){return c.getSharedPreferences(PREF,0).getBoolean("enabled",false);}
 static void scheduleDaily(Context c,int slot,int h,int m){AlarmManager am=c.getSystemService(AlarmManager.class);long when=next(h,m);int rc=BASE+slot;Intent i=new Intent(c,LaunchFeishuActivity.class).putExtra("slot",slot).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);ActivityOptions ao=ActivityOptions.makeBasic();if(Build.VERSION.SDK_INT>=34){ao.setPendingIntentCreatorBackgroundActivityStartMode(ActivityOptions.MODE_BACKGROUND_ACTIVITY_START_ALLOWED);}PendingIntent pi=PendingIntent.getActivity(c,rc,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE,ao.toBundle());Intent show=new Intent(c,MainActivity.class);PendingIntent showPi=PendingIntent.getActivity(c,rc+100,show,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);am.setAlarmClock(new AlarmManager.AlarmClockInfo(when,showPi),pi);c.getSharedPreferences(PREF,0).edit().putInt("h"+slot,h).putInt("m"+slot,m).apply();}
 static void cancelAll(Context c){AlarmManager am=c.getSystemService(AlarmManager.class);for(int s=0;s<2;s++){Intent i=new Intent(c,LaunchFeishuActivity.class);PendingIntent pi=PendingIntent.getActivity(c,BASE+s,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);am.cancel(pi);PendingIntent old=PendingIntent.getBroadcast(c,BASE+s,new Intent(c,AlarmReceiver.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);am.cancel(old);}setEnabled(c,false);}
 static long next(int h,int m){Calendar x=Calendar.getInstance();x.set(Calendar.HOUR_OF_DAY,h);x.set(Calendar.MINUTE,m);x.set(Calendar.SECOND,0);x.set(Calendar.MILLISECOND,0);if(x.getTimeInMillis()<=System.currentTimeMillis())x.add(Calendar.DAY_OF_YEAR,1);return x.getTimeInMillis();}
 @Override public void onReceive(Context c,Intent in){int s=in.getIntExtra("slot",0);c.getSharedPreferences(PREF,0).edit().putString("last_trigger",now()).apply();if(isEnabled(c)){int h=c.getSharedPreferences(PREF,0).getInt("h"+s,-1),m=c.getSharedPreferences(PREF,0).getInt("m"+s,-1);if(h>=0)scheduleDaily(c,s,h,m);}}
 static void launchFeishu(Context c,String src){Intent i=c.getPackageManager().getLaunchIntentForPackage("com.ss.android.lark");if(i==null){c.getSharedPreferences(PREF,0).edit().putString("last_launch",src+"失败：找不到飞书").apply();return;}i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_RESET_TASK_IF_NEEDED);try{c.startActivity(i);c.getSharedPreferences(PREF,0).edit().putString("last_launch",src+"成功 "+now()).apply();}catch(Exception e){c.getSharedPreferences(PREF,0).edit().putString("last_launch",src+"失败："+e.getClass().getSimpleName()).apply();}}
 static void createChannel(Context c){if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CHANNEL,"飞书定时启动",NotificationManager.IMPORTANCE_HIGH);c.getSystemService(NotificationManager.class).createNotificationChannel(ch);}}
 static String now(){return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.getDefault()).format(new Date());}
 static String diagnosticText(Context c){SharedPreferences p=c.getSharedPreferences(PREF,0);StringBuilder s=new StringBuilder("状态：").append(isEnabled(c)?"已启用":"未启用").append("\n");if(Build.VERSION.SDK_INT>=31)s.append("精确闹钟：").append(c.getSystemService(AlarmManager.class).canScheduleExactAlarms()?"已允许":"未允许").append("\n");if(Build.VERSION.SDK_INT>=34)s.append("全屏通知：").append(c.getSystemService(NotificationManager.class).canUseFullScreenIntent()?"已允许":"未允许").append("\n");s.append("最近一次闹钟触发：").append(p.getString("last_trigger","暂无")).append("\n最近一次启动飞书：").append(p.getString("last_launch","暂无"));return s.toString();}
}
